use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CleanupTarget {
    pub id: String,
    pub category: String,
    pub name: String,
    pub path: PathBuf,
    pub description: String,
    pub selected_by_default: bool,
    /// When true, scan immediate children instead of the target path as one item.
    pub expand_children: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CleanupCategory {
    pub id: String,
    pub name: String,
    pub description: String,
}

pub fn default_categories() -> Vec<CleanupCategory> {
    vec![
        CleanupCategory {
            id: "xcode".into(),
            name: "Xcode Junk".into(),
            description: "Intermediate build artifacts, device support files, and archives generated by Xcode. Safe to regenerate.".into(),
        },
        CleanupCategory {
            id: "caches".into(),
            name: "User Cache Files".into(),
            description: "Application cache files that speed up launches but can grow large over time.".into(),
        },
        CleanupCategory {
            id: "logs".into(),
            name: "User Log Files".into(),
            description: "Application and system log files. Usually safe to delete; apps recreate as needed.".into(),
        },
    ]
}

pub fn default_targets() -> Vec<CleanupTarget> {
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("/"));
    let library = home.join("Library");

    vec![
        // Xcode Junk
        CleanupTarget {
            id: "xcode-archives".into(),
            category: "xcode".into(),
            name: "Archives".into(),
            path: library.join("Developer/Xcode/Archives"),
            description: "Old .xcarchive bundles from App Store / ad-hoc distribution builds.".into(),
            selected_by_default: true,
            expand_children: true,
        },
        CleanupTarget {
            id: "xcode-ios-device-support".into(),
            category: "xcode".into(),
            name: "iOS Device Support".into(),
            path: library.join("Developer/Xcode/iOS DeviceSupport"),
            description: "Symbol files for physical iOS devices. Re-downloaded when you connect a device.".into(),
            selected_by_default: true,
            expand_children: true,
        },
        CleanupTarget {
            id: "xcode-derived-data".into(),
            category: "xcode".into(),
            name: "Derived Data".into(),
            path: library.join("Developer/Xcode/DerivedData"),
            description: "Build products, indexes, and module caches. Xcode rebuilds on next compile.".into(),
            selected_by_default: true,
            expand_children: true,
        },
        CleanupTarget {
            id: "xcode-macos-device-support".into(),
            category: "xcode".into(),
            name: "macOS Device Support".into(),
            path: library.join("Developer/Xcode/macOS DeviceSupport"),
            description: "Debug symbols for macOS targets. Regenerated when needed.".into(),
            selected_by_default: true,
            expand_children: true,
        },
        CleanupTarget {
            id: "xcode-watchos-device-support".into(),
            category: "xcode".into(),
            name: "watchOS Device Support".into(),
            path: library.join("Developer/Xcode/watchOS DeviceSupport"),
            description: "Debug symbols for watchOS devices.".into(),
            selected_by_default: true,
            expand_children: true,
        },
        CleanupTarget {
            id: "xcode-documentation-cache".into(),
            category: "xcode".into(),
            name: "Xcode Documentation Cache".into(),
            path: library.join("Developer/Xcode/DocumentationCache"),
            description: "Cached Apple developer documentation. Re-downloaded by Xcode.".into(),
            selected_by_default: true,
            expand_children: false,
        },
        CleanupTarget {
            id: "xcode-simulator-caches".into(),
            category: "xcode".into(),
            name: "Simulator temp caches".into(),
            path: library.join("Developer/CoreSimulator/Caches"),
            description: "Temporary dyld/Springboard caches under CoreSimulator/Caches only. \
                Does NOT delete installed simulators, apps, or data in CoreSimulator/Devices."
                .into(),
            selected_by_default: false,
            expand_children: false,
        },
        // User caches & logs — drill into top-level children
        CleanupTarget {
            id: "user-caches".into(),
            category: "caches".into(),
            name: "User Cache Files".into(),
            path: library.join("Caches"),
            description: "Per-application cache directories under ~/Library/Caches.".into(),
            selected_by_default: false,
            expand_children: true,
        },
        CleanupTarget {
            id: "user-logs".into(),
            category: "logs".into(),
            name: "User Log Files".into(),
            path: library.join("Logs"),
            description: "Per-application log directories under ~/Library/Logs.".into(),
            selected_by_default: false,
            expand_children: true,
        },
    ]
}

pub fn expand_path(path: &Path) -> PathBuf {
    if let Some(s) = path.to_str() {
        if let Some(rest) = s.strip_prefix("~/") {
            if let Some(home) = dirs::home_dir() {
                return home.join(rest);
            }
        }
        if s == "~" {
            if let Some(home) = dirs::home_dir() {
                return home;
            }
        }
    }
    path.to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_targets_have_unique_ids() {
        let targets = default_targets();
        let mut ids = std::collections::HashSet::new();
        for t in targets {
            assert!(ids.insert(t.id.clone()), "duplicate id: {}", t.id);
        }
    }
}
